import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import io from "socket.io-client";

const socket = io("http://localhost:5000");

export default function Home() {
  const [message, setMessage] = useState("");
  const [list, setList] = useState([]);
  

  const handleSendMessage = () => {
    //サーバーへ送信
    
    let element = document.getElementById('image_num');
    let q_number =Number(element.textContent);
    console.log("image_number=",q_number);
    socket.emit("send_message", { message: message , q_number: q_number});
  };

  const handleSendQuestion = () => {
    //サーバーへ出題リクエスト送信
    socket.emit("send_question",{});
  };

  //サーバーから受信
  socket.on("received_message", (data) => {
     console.log(data);
    setList([...list, data]);
    
  });

  //サーバーから画像受信
  socket.on('sendImage', (data) => {
    const imgElement = document.getElementById('imageViewer');
    //q_number = data.image_num;
    const passwordTag = document.querySelector("#image_num");
    passwordTag.innerText =data.image_num;

    imgElement.src = data.imgSrc;
    
    
});



  return (
    
    <div className={styles.container}>
      <span id="image_num"></span>
      <Head>
        <title>チャットアプリ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        
        <h2>AI絵クイズ</h2>
        <img id="imageViewer" width="640" height="360"></img>
        <div className={styles.chatInputButton}>
        <button
            onClick={() => {
              handleSendQuestion();
              setMessage("");
            }}
          >
            出題
          </button>
          </div>
        <div className={styles.chatInputButton}>
          <input
            type="text"
            onChange={(e) => {
              setMessage(e.target.value);
            }}
            placeholder=""
            value={message}
          />
          <button
            onClick={() => {
              handleSendMessage();
              setMessage("");
            }}
          >
            送信
          </button>
        </div>
        {/* {JSON.stringify(list)} */}
        <div>
          {list.map((_,i,chat) => (
            <div key={chat.message} className={styles.chatArea}>
              {chat[chat.length-1-i].message}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}